---
title: "Vignette"
author: "Kingsley David Onyewuchi Ofoegbu, Jazelle Pilao, Doudou Shi, and Evan Steinberg"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{my-vignette}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Use Case

# Required Packages

# Data Source and Structure

One of the data sources used in this project comes from The COVID Tracking Project. This project is comprised from volunteers from *The Atlantic*. These volunteers have the goal of collecting and publishing data related to the coronavirus pandemic specifically in the United States. This data source contains information regarding number of deaths, number of cases, number of tests, and more. Structurally, this data collects information for each of the 50 U.S. states, the District of Columbia, and 5 U.S. territories. Each observation is in terms of days. What this means is that, each day, 56 new observations get added to the data set representing the COVID data from each of the 56 states/territories tracked. This means that there are a total of 14,730 observations with the first data being reported on January 22 (The COVID Tracking Project, 2020).

Another data source used comes from Ballotpedia. This source gives information on the political party of each of the state governors, including the governors of 5 U.S. territories. In terms of structure, this data has one row for each state/U.S. territory. In this row, there is the name of the state and the party the governor belongs to (Ballotpedia, 2020).

Another source used is from the U.S. Census. This source contains information regarding the population of the United States broken down by state. This source also contains information for the District of Columbia and Puerto Rico. In terms of structure, each state has its own row. In addition, the District of Columbia has a row, as does Puerto Rico. Furthermore, there is a row for the United States overall, and four different regions: Northeast, Midwest, South, and West. Each row contains information regarding the population from 2010 to 2019. Each row has the popoulation totals for each of those 10 years, the percent increase over the years, number of deaths, births, etc. For a complete list of the variables in this data set, please consult the data dictionary [here](https://www2.census.gov/programs-surveys/popest/technical-documentation/file-layouts/2010-2019/nst-est2019-alldata.pdf). (U.S. Census Bureau, 2019)

An additional data source used in this app is another source from the Center for Disease Control (CDC), specifically the National Center for Health Statistics. This source contains specifications on COVID-19 deaths broken down by state, age and gender. Age is separated into 10 groups, starting with a group of 18 – 29 and ending with a group of 85 and over. State is separated into the 50 states and includes the District of Columbia and Puerto Rico. Gender is split into two genders: male and female. This dataset additional has total counts for the entire country.  In terms of structure this data source has 20 rows for each state with separate rows by age group and by gender. The cleaned dataset used in this app includes 4 columns for state, gender, age group and total deaths. For more information about this data source and the CDC data collection , please consult the following link [here] (https://data.cdc.gov/NCHS/Provisional-COVID-19-Death-Counts-by-Sex-Age-and-S/9bhg-hcku). (Center for Disease Control, 2020)

# EDA Inputs, Controls, and Outputs

You will be able to visualize compare confirmed cases and deaths due to COVID-19 by age, by gender, by pre-existing conditions, by month, and by state in the United States. These will be visualized in two ways. First, you will be able to look at boxplots comparing the distribution of COVID-19 deaths for each group in the variable. In addition, you will also be able to look at bar graphs to look at which group has the most COVID-19 cases. You will also be able to visually investigate the relationship of age, existing conditions, and location (by state) to total COVID positive test results, extreme progression of the virus (individuals on ventilators), and COVID deaths. You will be able to see these relations through boxplots to get a sense of the distribution, bar graphs to get a sense of the total numbers, and a written summary output generated for each visualization. For each of the boxplots created you will have the choice as to whether include outliers in the graph or not. If you choose to not include outliers, the x-axis will undergo a log base 10 transformation. In addition, there are boxplots presented for the overall distribution of COVID-19 deaths, positive test results, and extreme progression of the virus (individuals on ventilators). 

Furthermore, you will be able to look at COVID-19 related facts on a map. On this map, you can choose whether to visualize COVID-19 deaths, number of positive test results, or number of negative test results. Once you select which of those three you would like to explore more, a map of the United States will appear, where each state is a different shade of red. The darker shade of red the state is, the more of that input there is. For example, if you choose "death" as what you would like to explore, the darker shade of red a state is the more deaths there are in that state compared to the other states. It is important to note that these are totals for the entire pandemic, not for specific months. In addition, if you were to click on any state on the map, the name of the state, as well as the number for that state would be presented. On the map, you can choose to zoom in, zoom out, or move around more to focus on specific regions/states as needed. In addition, you can choose whether the map resents the total numbers, or the numbers per 100,000 people. The numbers per 100,000 people will make the comparision of states more comparable, because it accounts for the population of people in that state.

# Statistical Analysis Inputs, Controls, and Outputs

Based on the input you choose for the mapping, different t-tests will be run. They will compare whether the political party of state's governors affect the number of COVID-19 deaths, positive test results, or negative test results. Whichever you choose to visualize on the map of the United States will be the same variable used in this t-test. The app presents the p-value, estimate, and 95% confidence interval from the t-test. If the p-value is below 0.05, then there is evidence that the political party of the governor affects the input variable, and you can conclude that the estimate is statistically different than 0. In addition, you can conclude with 95% confidence that the true value of the input falls between the lower and upper bounds of the 95% confidence interval. If you choose to do the mapping per 100,000 people, the t-test changes slightly. The interpretation and baseline concepts discussed above are still applicable. However, the numbers will be per 100,000 people. Therefore, the interpretation will change and your conclusions will be made for 100,000 people.

# References
The COVID Tracking Project (2020). Our Data. https://covidtracking.com/data/download.

Ballotpedia (2020).Partisan Composition of Governors.  https://ballotpedia.org/Partisan_composition_of_governors

 U.S. Census Bureau (2019). 2019 National and State Population Estimates. https://www.census.gov/newsroom/press-kits/2019/national-state-estimates.html.

